environment:
  image: charliek/ci-java:openjdk7-gradle19
  language: java
  vars:
    GRADLE_OPTS: "\"-Xms56m -Xmx256m -XX:MaxPermSize=256m -XX:+CMSClassUnloadingEnabled\""

build:
  before_install:
    - curl -L -o etcd.tar.gz https://github.com/coreos/etcd/releases/download/v0.2.0/etcd-v0.2.0-Linux-x86_64.tar.gz
    - tar zxf etcd.tar.gz
    - export PATH=./etcd-v0.2.0-Linux-x86_64:$PATH
  run:
    - ./gradlew clean test withEtcd check
